cockroachdb/molt

cmd/verify/verify.go
datamove/dataexport/dataexport.go
go.mod
rowiterator/scan_iterator.go
verify/rowverify/live_reverifier.go
verify/rowverify/live_reverifier_test.go
verify/rowverify/rowverify.go
verify/verify.go
verify/verify_test.go

verify: add `--rows-per-second`
This commit adds a `rows-per-second` flag, which if set, limits rows
scanned to that amount per shard.
verify: add `--live-runs-per-second`
Which enforces how often the live reverifier can go about reverifying a
batch.
rowverify: add metrics to live reverifier

verify: add `--rows-per-second`, `--live-runs-per-second`, metrics

---

README.md
dbconn/dbconn.go
mysqlconv/data_type.go
mysqlconv/data_type_test.go
mysqlconv/datum_converter.go
mysqlconv/testdata/datatype/datatype.ddt
verify/tableverify/tableverify.go
verify/testdata/datadriven/mysql/enum.ddt

This commit allows enum comparisons between MySQL enums and CRDB.

mysqlconv: add enum comparisons

---

.github/docker-compose.yml
.github/workflows/go.yaml
README.md
cmd/fetch/fetch.go
fetch/dataexport/crdb.go
fetch/dataexport/dataexport.go
fetch/dataexport/mysql.go
fetch/dataexport/pg.go
fetch/dataexport/pg_test.go
fetch/fetch.go
fetch/fetch_test.go
testutils/conn.go

This commit ensures that `row-batch-size` is configurable when reading
rows from the database.
This commit adds the ability for `fetch` to create a data replication
slot for later use.

dataexport: automatically create a pg replication slot if requested 

---

cmd/verify/verify.go
verify/verify.go

This commit adds a `--rows` flag, which defaults to `true`. If disabled, this will disable any row based checks.
This is useful for tools like DMS verification, in which this ensures schemas match between the two sides.

verify: add a --rows flag

---

dbconn/mysql.go
mysqlurl/parse.go
mysqlurl/parse_test.go

Previously, when using a connection string to parse and reformatting it back as a DSN, the TLS config is lost as the field is not set nor the TLS config registered to the driver. Resolve this by registering any parsed config.

mysqlurl: register TLS config when parsing using connection string

---

dbconn/dbconn.go

Previously, we omitted the `mysql://` part which was an artifact of the old parsing mechanism. fix that.

dbconn: correctly pass in MySQL connection string

---

charts/lms/Chart.yaml
charts/lms/templates/_helpers.tpl
charts/lms/templates/lms-deployment.yaml
charts/lms/templates/lms-role.yaml
charts/lms/templates/lms-service.yaml
charts/lms/templates/lms-serviceMonitor.yaml
charts/lms/templates/orchestrator-deployment.yaml
charts/lms/templates/orchestrator-service.yaml
charts/lms/templates/orchestrator-serviceMonitor.yaml
charts/lms/templates/serviceaccount.yaml
charts/lms/values.yaml

This commit adds the production helm chart for the LMS. It will deploy the LMS and Orchestrator by itself with full customization over how you want to configure it. There is an optional service monitor that can be installed if running with the prometheus operator.

LMS: Add Helm Chart

---

.github/workflows/release-helm.yaml

- Add environment references so that bucket names and URLs can be conditional for environment
- Add in basic versioning
- Pull old index and merge with existing
- Upload to bucket after authing with Google

.github/workflows: productionize Helm chart publishing

---

.github/workflows/release-helm.yaml

The command should be using the URL-mao name instead of the CDN name.

Fix CDN invalidation command

---

cmd/fetch/fetch.go
fetch/csv_pipe.go
fetch/csv_pipe_test.go
fetch/export_table.go
fetch/fetch.go

Added in an optimization parameter so that users can control the number of rows after for the exportTable job to flush.
Resolves: #14

fetch: added in the config flag/option for configuring a number of rows to flush after

---

fetch/datablobstorage/local.go
fetch/fetch.go
fetch/import_table.go
fetch/import_table_test.go
fetch/testdata/csv/import_basic_000.csv

Added in a Go routine that repeatedly queries the database for the IMPORT job and reports progress to the STDOUT.
Action items:

fetch: added in progress indicator for the import table jobs

---

.github/workflows/go.yaml
.github/workflows/release.yaml
go.mod

This commit bumps the molt repo to build the binaries with golang version 1.21.

MOLT: Bump to build with Go 1.21

---

docker/docker-compose.yml
docker/mysql-init/mysql-init.sql
docker/pg-init/pg-init.sql

This commit adds a basic docker compose for testing purposes. Right now it only spins up mysql with the database and a single row

MOLT: Add docker-compose

---

README.md
cmd/fetch/fetch.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/s3.go

Previously, intermediate files were only able to be written to the top level of a bucket. This changes the logic so that it's now possible to write to sub paths, which allows for more flexibility and reuse.
Action items

fetch: added the ability to write intermediate export files to sub paths within a bucket

---

cmd/fetch/fetch.go

Previously, compression was applied for a default for both the non-live mode and direct copy without the live flag. This made the writer for copy compressed by default, leading to an issue when copying. This change makes it so that we don't allow compression while copying and updating the default logic so that we can properly pass in compression opts.
Resolves: #60 
**Test Run**
```
(⎈|rancher-desktop:N/A)ryanluu@crlMBP-XFFK6Q9QL6MTk1 molt % go run . fetch \
--source 'postgres://postgres:migrations@molt-test-pg.cpa6lrp2ahsc.us-east-1.rds.amazonaws.com:5432/sourcedb' \
--target 'postgres://root@localhost:26257/defaultdb?sslmode=disable' \
--table-filter 'employees' \
--s3-bucket molt-test --compression default
<nil> INF default compression to gzip
<nil> INF checking …
```

fetch: fixed direct-copy functionality and disallow compression for COPY modes

---

fetch/dataexport/mysql.go

Now prompts the user the check that GTID-based replication is enabled before running with MOLT fetch.
Resolves: #53 

fetch: added clearer help text when MySQL gtid_executed table not set up

---

cmd/fetch/fetch.go
cmd/internal/cmdutil/dbconn.go
cmd/internal/cmdutil/logger.go
cmd/internal/cmdutil/name_filter.go
cmd/root.go
cmd/verify/verify.go

Made the command descriptions and flags have consistent formatting. Prioritizing full sentences and better clarity about what each flag does for both fetch and verify. Also made the help command and autocomplete hooks so that it has behavior we expect. Removed the autocomplete command because that is extraneous.
Resolves: #59

molt: made the command flags and descriptions consistent with other migrations tooling

---

.github/workflows/release.yaml
Makefile
climanifest/README.md
climanifest/base-versions.txt
climanifest/climanifest.go
climanifest/climanifestHtml.tmpl
go.mod
go.sum
scripts/build-cross-platform.sh

**molt: added in script to build tool cross platform and updated Makefile entries**
Added in a helper script so that we build out the tooling in a more standardized way.
Also updated `go-ole` to the latest version in order to address build issues with Windows + Arm64.
**climanifest: added in manifest generation code that outputs an HTML manifest for versions**
This is the common package that will be used across MOLT tools to generate manifest for binaries.
**.github/workflows: added release-cli workflow steps to upload to GCS bucket**
Added logic to run cross platform builds, update the manifest, and upload the manifest and new builds to GCS. Invalidates the cache afterwards.
Removed legacy release steps.

molt: unify the release process

---

mysqlconv/data_type.go
mysqlconv/testdata/datatype/datatype.ddt

This commit adds support for the mediumtext and longtext types in MySQL. They will be tranlsated to the string type in CRDB
This commit also fixes the panic error message for unhandled types to properly show which data type caused the problem.
Release note: Additional supported MySQL types

Verify: Support additional MySQL types

---

.githooks/commit-msg
.github/workflows/release.yaml
Makefile
README.md

Gets the log between the head of the branch and the latest release tag. Then creates a ticket with the relevant fields, using the official JIRA GH action helper.
Resolves: CC-26297, CC-26370
Release Note: Release notes are now more structured and describe customer implications more clearly. These notes are now picked up by automation and will be reflected in documentation pages.
Test run: https://github.com/cockroachdb/molt/actions/runs/7038865628
Created ticket: https://cockroachlabs.atlassian.net/browse/DOC-9302

.github/workflows: automate the docs creation ticket after release

---

README.md

Added details about setting up replication using GTIDs so that people can have their MySQL instance ready for use with MOLT fetch. GTID is required because it is a necessary step for returning the cdc_cursor.
Resolves: CC-26359
Release Note: README for MOLT fetch is now updated with MySQL specific setup instructions that instruct users to set up replication using GTID, which is required for MOLT fetch to operate with MySQL correctly. This change will clarify confusion users had about MOLT fetch instructions not working because of a missing pre-condition step.

README: added specific MySQL setup instructions

---

cmd/fetch/fetch.go
cmd/internal/cmdutil/logger.go
cmd/verify/verify.go

Resolves: CC-26366, CC-26376
Release Note: Logging for the Fetch and Verify tooling is now defaulted to structured JSON logging which contains at least the message, level, and formatted time string. There is now a flag that can set the output to use prettier console writing that has colored output and human readable output. The structured logging is preferred as a default because it's easier to parse by log ingestion tools and is more efficient to output by the application. Also, customers can now define log files to write their task/data logs for fetch and verify. If left empty, the molt tool will only write to stdout, which is more efficient.
**Decisions**
- Defaulted to not writing out to a log file + stdout because it's less performant; most customers will probably want to just pick …

cmdutil: refined logging scheme by adding timestamps, structured logging as a default, and option to write to a log file

---

cmd/fetch/fetch.go

Release Note: Marked the s3-bucket, gcp-bucket, and local-path flags as mutually exclusive because they all represent different intermediary stores. Also, marked settings for the flush rows and byte size so that only one policy can apply at a time.
Test Results:
```
(⎈|rancher-desktop:N/A)ryanluu@crlMBP-XFFK6Q9QL6MTk1 molt % go run . fetch --source "ya" --target "nah" --flush-size 10 --flush-rows 100                  
Error: if any flags in the group [flush-size flush-rows] are set none of the others can be; [flush-rows flush-size] were all set
(⎈|rancher-desktop:N/A)ryanluu@crlMBP-XFFK6Q9QL6MTk1 molt % go run . fetch --source "ya" --target "nah" --s3-bucket s3 --gcp-bucket gcp 
Error: if any flags in the group [s3-bucket gcp-bucket local-path] are set none of the others can be; …
```

fetch: marked certain flags as mutually exclusive so that multiple modes cannot be run at once

---

cmd/fetch/fetch.go
cmd/verify/verify.go
fetch/copy.go
fetch/csv_pipe.go
fetch/fetch.go
fetch/import_table.go
moltlogger/logger.go
utils/time.go
utils/time_test.go

Added in logger types and Zerolog log context so that logs can be tagged with different contextual information. Also added utility methods that allow a user to retrieve a summary or data logger from their base logger.
Resolves: CC-26366
Release Note: Added tagging for summary and data logs so that customers can filter by "summary" or "data" in a variety of log processing tools and even grep in the command line. This solves the pain point of all the logs going to the same location without any differentiation. Now it's possible to view types of logs one at a time.
**Options Considered**
1. Making a base logger with the type already set => good solution and almost like the solution presented here, however, this led to duplicated `type` fields because zerolog doesn't de-duplicate repeated …

molt: added in logger field for type to differentiate between task, summary, and data logging

---

cmd/verify/verify.go
verify/inconsistency/reporter.go
verify/inconsistency/stats.go
verify/rowverify/row_event_listener.go
verify/rowverify/rowverify.go
verify/testdata/datadriven/mysql/casing.ddt
verify/testdata/datadriven/mysql/collation.ddt
verify/testdata/datadriven/mysql/enum.ddt
verify/testdata/datadriven/mysql/row_mismatch.ddt
verify/testdata/datadriven/pg/collation.ddt
verify/testdata/datadriven/pg/database_mismatch.ddt
verify/testdata/datadriven/pg/row_mismatch.ddt
verify/testdata/datadriven/pg/shard_table.ddt
verify/testdata/datadriven/pg/table_mismatch.ddt

**Change 1**
Made the summary stats report the stats in the log as individual fields in JSON so that they can more easily be filtered and extracted. Previously, this would require regex extraction, but now can be indexed directly.
Release Note: Changed the output for the running summary statistics so that they are now more easily indexable by log processing tools. Previously, it was more human readable, but fields were not indexable easily out of the box. Now, there is a balance between readability and downstream processing.
**Change 2**
verify: updated reporting to use data and summary loggers in correct places
Verify centralizes logging in a LogReporter struct. Currently, they all log to the same task logger, but the change here is to get the appropriate loggers and annotate the lo gs …

verify: refactored the stats and inconsistency reporting so it's in exported from the inconsistency package

---

cmd/internal/cmdutil/flags.go
cmd/internal/cmdutil/flags_test.go
cmd/verify/verify.go

Previously, flags were grouped together by the MarkFlagRequiredTogether method that Cobra supplies. This ends up having the downside that all flags marked together must be set, which makes for a worse UX because people need to supply more flags instead of relying on sane defaults.
The change here is to introduce a concept of dependencies so that a flag can mark a one-directional dependency to another flag so that if a child is set without the parent dependency, it will error out. But if the parent is set, the child doesn't necessarily need to be set.
Release Note: Release Note: Marked the "live" and "continuous" flags as dependencies for other sub-configuration flags. Disregard the MarkFlagRequiredTogether note from above. This provides a clearer user experience so that if a flag is set …

verify: made a helper to check dependency of flags on a root flag

---

docker/docker-compose.yml
docker/grafana/dashboard.yaml
docker/grafana/datasource.yml
docker/prometheus/prometheus.yml

Added in the scaffolding for containers to collect prometheus metrics and view them with Grafana. Added in several TODOs for updating the dashboard, which will be addressed in a future PR.
Resolves: CC-26355
**Screenshots**

docker: added in prometheus and grafana containers to view MOLT metrics

---

docker/cockroach-init/cockroach-init.sql
docker/mysql-init/mysql-init.sql
docker/pg-init/pg-init.sql
verify/inconsistency/reporter.go
verify/inconsistency/row.go
verify/inconsistency/stats.go
verify/rowverify/live_reverifier.go
verify/rowverify/live_reverifier_test.go
verify/rowverify/row_event_listener.go
verify/rowverify/rowverify.go
verify/tableverify/tableverify.go
verify/testdata/datadriven/mysql/casing.ddt
verify/testdata/datadriven/mysql/collation.ddt
verify/testdata/datadriven/mysql/column_type_mismatch.ddt
verify/testdata/datadriven/mysql/enum.ddt
verify/testdata/datadriven/mysql/row_mismatch.ddt
verify/testdata/datadriven/pg/collation.ddt
verify/testdata/datadriven/pg/database_mismatch.ddt
verify/testdata/datadriven/pg/row_mismatch.ddt
verify/testdata/datadriven/pg/shard_table.ddt

TLDR; we prevent panics and mark the row now as a mismatch if columns mismatch.
Previously, if a comparison between heterogeneous types occurred, verify would panic and stop execution. With this change to use CompareError instead of Compare, verify no longer panics, but rather records the error and reports it to the logging and also marks the row as mismatched, which semantically is correct because even if values are the same, they are different types.
@rafiss recommended converting usage from `Compare` to `CompareError` so that we can handle the error on our side and figure out what to do when it happens.
**Tests**
Before
```
{"level":"info","time":"2023-12-13T13:12:25-08:00","message":"starting verify on public.employees, shard 1/1"}
panic: unsupported comparison: …
```

verify: switched usage from Compare to CompareError to resolve panic

---

cmd/verify/verify.go
fetch/csv_pipe.go
fetch/fetchmetrics/metrics.go
verify/inconsistency/reporter.go
verify/rowverify/live_retry_queue.go
verify/rowverify/live_reverifier.go
verify/rowverify/row_event_listener.go
verify/verify.go
verify/verifymetrics/metrics.go

Added in a new package responsible for centralizing high level metrics for verify. We now track more detailed types of metrics about the tables processed and their category: verified, missing, extraneous. Additionally, moved some high level metrics to this new package so that all metrics are colocated for other devs to review.
Resolves: CC-26355
Release Note: Added in new metrics for consumption in dashboards - molt_verify_num_tables (split up by category), molt_verify_duration_ms (to see how long a MOLT run took).
**Testing Results**
```
molt_verify_duration_ms 4760
molt_verify_num_tables{category="extraneous"} 0
molt_verify_num_tables{category="missing"} 1
molt_verify_num_tables{category="verified"} 1
molt_verify_num_row_fixups{category="extraneous"} 0 …
```

verify: added in high level metrics for verify and refactored into the verifymetrics package

---

.githooks/prepare-commit-message

Just feeling lazy to type `Release note:` every time when committing, so adding it in the commit message template. This is following the CockroachDB main repo: https://github.com/cockroachdb/cockroach/blob/ba84e57f38d31b85758b6c9ff305bf7d07752f25/githooks/prepare-commit-msg
To make it take effect, please do
```
chmod ug+x .githooks/*
make sync_hooks
```
After this change, the `git commit` will prompt with these additional lines
```
#Release note: None
#Release note (bug fix): 
```

githook: add Release note in commit message template

---

cmd/fetch/fetch.go
fetch/copy.go
fetch/csv_pipe.go
fetch/datablobstorage/datablobstorage.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/local.go
fetch/datablobstorage/s3.go
fetch/fetch.go
fetch/fetchmetrics/metrics.go
fetch/import_table.go

Previously, we only tracked metrics for the number of imported rows. This change aims to add details about progress, durations, errors/exceptions encountered, and the number of tables involved. The metrics will be plumbed through the codebase and capture meaningful data that will allow folks to understand the performance and stability of the system.
Resolves: CC-26354
Test Run Results:
```
molt_fetch_num_tables 1
molt_fetch_num_task_errors 0
molt_fetch_overall_duration 5.274946125
molt_fetch_rows_imported{schema="public",table="public.employees"} 200000
molt_fetch_table_export_duration_ms{schema="public",table="public.employees"} 1897
molt_fetch_table_import_duration_ms{schema="public",table="public.employees"} 3257 …
```

fetchmetrics: added all metric types and metric initializers

---

docker/docker-compose.yml
docker/grafana/dashboard.json

Added in MOLT fetch metrics which shows counts, rates, etc. by tables.
Made a variable that allows you to filter the search of the tables you want to look at.

docker/grafana: added initial cut for MOLT dashboard

---

utils/formatting.go
verify/inconsistency/reporter.go
verify/rowverify/row_event_listener.go
verify/verifymetrics/metrics.go

As you can see here in the testing, there is now the table label:
```
molt_verify_duration_seconds 0.732952792
molt_verify_num_row_fixups{category="extraneous",table="overall"} 0
molt_verify_num_row_fixups{category="mismatching",table="overall"} 0
molt_verify_num_row_fixups{category="missing",table="overall"} 0
molt_verify_num_row_fixups{category="mismatching",table="public.employees"} 1
molt_verify_num_tables{category="extraneous"} 0
molt_verify_num_tables{category="missing"} 0
molt_verify_num_tables{category="verified"} 1
molt_verify_row_verification_status{status="conditional_success",table="overall"} 0
molt_verify_row_verification_status{status="extraneous",table="overall"} 0
molt_verify_row_verification_status{status="mismatching",table="overall"} 0 …
```

verifymetrics: added table label to verify metrics so that we can see issues by table

---

docker/grafana/dashboard.json

Added in a new panel that has the top level metrics as single stats and then shows each of the row data as time visualization.

docker/grafana: added dashboard section for verify

---

fetch/status/exceptions.go
fetch/status/exceptions_test.go
fetch/status/status.go
fetch/status/status_test.go
fetch/status/utils.go

The helpers include mapping structs, helpers to create and update resources in the database, constants to represent different states.
Resolves: CC-26805
**Tested with this bit of code**
```
// TODO: logic for seeing source dialect
targetPgxConn := conns[1].(*dbconn.PGConn).Conn
if err := status.CreateStatusAndExceptionTables(ctx, targetPgxConn); err != nil {
return err
}
fetchStatus := status.FetchStatus{
Name:          "the-best",
Status:        status.StatusInProgress,
StartedAt:     time.Now(),
SourceDialect: "PostgreSQL",
}
if err := fetchStatus.Create(ctx, targetPgxConn); err != nil {
return err
}
fmt.Println(fetchStatus.ID)
fetchException := status.ExceptionLog{
FetchID:  fetchStatus.ID,
FileName: "yo.log",
Table:    "employees",
Schema:   "public",
Message:  "it …
```

fetch: added in status and exception database helpers

---

Makefile
cmd/fetch/fetch.go
fetch/csv_pipe.go
fetch/export_table.go
fetch/fetch.go
fetch/fetch_test.go
fetch/import_table.go
fetch/testdata/pg/exceptions.ddt
testutils/knobs.go

Added in testing knobs structure and formatting so that we can properly simulate errors. Currently, the corrupt CSV failure mode is simulated for better testing.
Resolves: CC-26918

fetch: added in testing knobs to simulate corrupted CSV failures

---

cmd/fetch/fetch.go
fetch/fetch.go

This commit adds the 3 new flags that will be needed for the continuation process work. Fetch-id is the parent flag and is a dependency for the child flags continuation-token and continuation-file-name.

[CC-26908] fetch: Add new flags for continuations

---

cmd/fetch/fetch.go
fetch/csv_pipe.go
fetch/csv_pipe_test.go
fetch/datablobstorage/copy_direct.go
fetch/datablobstorage/datablobstorage.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/gcp_test.go
fetch/datablobstorage/gcp_testutil.go
fetch/datablobstorage/local.go
fetch/datablobstorage/s3.go
fetch/datablobstorage/s3_testutils.go
fetch/export_table.go
fetch/export_table_test.go
fetch/fetch_test.go
testutils/knobs.go
testutils/local_store.go

(Authored by @Jeremyyang920)
This commit adds a row count field to ever storage resource. The reason for this is mainly for progress tracking but more specfically for the IMPORT use case where we are not able to know the number of rows imported. We now have this information since each resource has its own file count.
----
Previous, if error happens when writing result to the storage (gcp/aws/local),
the error won't be properly propagated back to the main routine in exportTable(),
causing the main routine to hang.
This patch is to fix it so that the main process exits in this case.
Context:
- https://cockroachlabs.slack.com/archives/C04TQ67V1JL/p1705445765473889
- https://github.com/cockroachdb/molt/pull/114#discussion_r1453968635
Release note (bug fix): resolve deadlock …

fetch: fix csv pipe deadlock + add row count per file to blob resource

---

fetch/import_table.go
fetch/import_table_test.go
fetch/status/exceptions.go
fetch/status/exceptions_test.go
go.mod
go.sum

This commit adds the logic to allow bisecting a batch of files from import that failed to try and narrow down the problem file to record in the exceptions table.

[CC-27092] fetch: Add bisect logic for import

---

cmd/fetch/fetch.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/local.go
fetch/datablobstorage/s3.go
fetch/fetch.go
fetch/fetch_test.go
fetch/status/exceptions.go
fetch/testdata/pg/continuation.ddt
utils/formatting.go
utils/formatting_test.go

Added in logic for the import/copy only mode that skips the export phase if fetch id or continuation token is passed in. Also integrated with the logic to continue from a certain file point.
Resolves: CC-26910

fetch: integrate continuation with fetch uploaded resources and exception logs

---

Makefile
fetch/fetch.go

Success
```
{"level":"info","type":"summary","net_duration_ms":1909.038584,"net_duration":"000h 00m 01s","import_duration_ms":1550.864625,"import_duration":"000h 00m 01s","export_duration_ms":354.458375,"export_duration":"000h 00m 00s","num_rows":200000,"cdc_cursor":"0/3F5ABD0","time":"2024-02-07T12:06:12-05:00","message":"data import on target for table complete"}
{"level":"info","type":"summary","fetch_id":"f6cd1d37-98a6-4620-9188-671a1e1ced7d","num_tables":1,"tables":["public.employees"],"cdc_cursor":"0/3F5ABD0","net_duration_ms":1946.456708,"net_duration":"000h 00m 01s","time":"2024-02-07T12:06:12-05:00","message":"fetch complete"}
```
Failure
```
{"level":"info","fetch_id":"011fe845-117d-4533-bf6b-5e8506da355a","time":"2024-02-07T12:06:47-05:00","message":"continue from this fetch …
```

fetch: fix continue logging so it only logs on error

---

utils/formatting.go

Test results:
```
{"level":"info","time":"2024-02-08T18:25:30-05:00","message":"starting data import on target"}
{"level":"info","table":"public.employees","continuation_token":"e271639b-e55b-4735-887a-709655e144a0","time":"2024-02-08T18:25:50-05:00","message":"created continuation token"}
{"level":"info","fetch_id":"96b99aff-1538-4e68-a9cd-9c3cec063d46","time":"2024-02-08T18:25:50-05:00","message":"continue from this fetch ID"}
```

fetch: fix MaybeFormatFetchID so that it uses the correct format fetch ID in non test mode

---

fetch/datablobstorage/datablobstorage.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/gcp_test.go
fetch/import_table.go

We want to track the number of rows per file so we can know how many rows have been imported as we do the import. Additionally, fixed a couple bugs: potential deadlock, panic because of invalid store passed in, etc.
Resolves: CC-27046
Runs properly (verified it logs out the number of rows per resource)
```
&{0x140004d8d80 public.employees/part_00000001.tar.gz 200000}
```
```
(⎈|rancher-desktop:N/A)ryanluu@crlMBP-XFFK6Q9QL6MTk1 molt % go run . fetch \             
--source 'postgres://postgres:postgres@localhost:5432/molt?sslmode=disable' \
--target 'postgres://root@localhost:26257/defaultdb?sslmode=disable' \
--table-filter 'employees' \
--gcp-bucket migrations-fetch-ci-test --fetch-id 6c81abeb-187a-41f8-ada6-c29c66684b36 …
```

fetch: added numrows metadata to file upload for GCP

---

fetch/datablobstorage/datablobstorage.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/gcp_test.go
fetch/datablobstorage/s3.go
fetch/datablobstorage/s3_test.go

Added in concurrency for listing from continuation point so we don't block on our request to get specific metadata details per each file. Also added in the calls to external APIs and the upload metadata line.
Resolves: CC-27046
Test Results:
```
{"level":"warn","time":"2024-02-07T17:18:07-05:00","message":"skipping export for table public.employees due to running in import-copy only mode"}
map[Numrows:0x14000c352f0]
map[Numrows:0x140008f0110]
map[Numrows:0x140008f0270]
map[Numrows:0x140008f0320]
&{0x140006fd080 0x1400092eff0 public.employees/part_00000001.tar.gz 10} &{0x140006fd080 0x1400092eff0 public.employees/part_00000002.tar.gz 10} &{0x140006fd080 0x1400092eff0 public.employees/part_00000003.tar.gz 10} &{0x140006fd080 0x1400092eff0 …
```

fetch: added in upload metadata for S3

---

fetch/datablobstorage/gcp.go
fetch/pipe.go

This commit updates the comment around why we created our own pipe object.
Release Note: none

fetch: Update pipe comment

---

README.md

According to the codebase, Fetch uses COPY FROM and not COPY TO.

revise COPY TO to COPY FROM in readme

---

docker/cockroach-init/cockroach-init.sql
docker/pg-init/pg-init.sql
fetch/copy.go
fetch/datablobstorage/copy_direct.go
fetch/datablobstorage/datablobstorage.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/local.go
fetch/datablobstorage/s3.go
fetch/fetch.go
fetch/fetch_test.go
fetch/import_table.go
fetch/internal/dataquery/dataquery.go
fetch/testdata/pg/direct.ddt

Resolves: CC-27188
Existing CI passing should be enough to validate this works.
Manually tested too:
```
molt_fetch_overall_duration 1.3976359999999999
molt_fetch_rows_exported{table="public.employees"} 200000
molt_fetch_rows_imported{table="public.employees"} 200000
```

fetch/datablobstorage: support local files numRows metadata

---

fetch/datablobstorage/gcp.go

This commit allows the gcp resource to create an import url for implicit auth. This will be used when users do not specify the gcp env var or have a credential file in the well known location.
Release Note: Adds implicit auth for gcp

[CC-27909] fetch: Add implicit auth for gcp

---

.github/workflows/release.yaml

Previously, characters were not getting escaped. Add quotes around fields so that they are properly escaped.
Reference: https://stackoverflow.com/questions/61795201/github-action-failed-syntax-error-near-unexpected-token

.github/workflows: fix create release ticket workflow

---

mysqlconv/data_type.go
mysqlconv/data_type_test.go
mysqlconv/datum_converter.go
mysqlconv/datum_converter_test.go
mysqlconv/testdata/rowvalue/bits.ddt
mysqlconv/testdata/rowvalue/time.ddt
pgconv/testdata/rowvalue/bits.ddt
verify/tableverify/query.go

Previous, the conversion of the bits type value from mysql to crdb is wrong, as it didn't correctly parse the value passed via the []uint8 val variable. We will get a 
```
22P02 Wraps: (2) could not parse string as bit array: "" is not a valid binary digit
```
error when trying to convert something like `b'11110000011'` into a `*tree.DBitArray`.
This PR is to fix it and add tests for it. 
Also added support for converting the time type.
Release note (bug fix): enable conversion of bit type entry from mysql to crdb. Add support for time type conversion too.

mysqlcov: fix for bits conversion, support time conversion

---

fetch/fetch.go

Added logging for when we try to run truncate on import/copy only mode. Only allow truncate for full runs that don't try to continue in order to minimize risk of missing data.
Data could be missing if truncate happens because truncate removes all the data from a table. If a continuation is run on a file other than the first one, at least one section of the data will be removed. Truncate is now only allowed in the full run mode.
```
(⎈|rancher-desktop:N/A)ryanluu@crlMBP-XFFK6Q9QL6MTk1 molt % go run . fetch \
--source 'postgres://postgres:postgres@localhost:5432/molt?sslmode=disable' \
--target 'postgres://root@localhost:26257/defaultdb?sslmode=disable' \
--table-filter 'employees' \
--local-path-listen-addr '0.0.0.0:9005' --bucket-path s3://molt-test --fetch-id …
```

fetch: disallow truncate for import/copy only mode

---

fetch/fetch.go
fetch/fetch_test.go
fetch/testdata/pg/continuation-edge-cases.ddt

Previously, when no exception logs for a given token were found, we would silently operate and not let the user know. Now we error and let the user know that there were no exception logs found, which helps the user to use a valid token. This could lead to less confusing behavior.
This change also adds coverage for the following cases:
- Continuing from a file greater than part 1
- If a continuation token is no longer present, we error and let user know
- If a continuation token links to an exception log that doesn't have a file name, we error out because no file name is present
Resolves: CC-27047

fetch: added better testing for continuation and fixed behavior for no exceptions log found

---

.github/workflows/e2etest.yaml
.github/workflows/go.yaml
.github/workflows/release.yaml
go.mod

This commit bumps the molt repo to use go 1.22 for testing.

MOLT: Bump to go 1.22

---

cmd/fetch/fetch.go
fetch/copy.go
fetch/datablobstorage/copy_direct.go
fetch/fetch.go
fetch/fetch_test.go
fetch/import_table.go
fetch/status/exceptions.go
fetch/testdata/pg/continuation-edge-cases.ddt
fetch/testdata/pg/continuation.ddt

The behavior introduced makes it so that customers only have one set of continuation tokens that are tied to a single fetch ID. This solves the problem of not using stale tokens that may correspond to older versions of the data set. At a high level, this is the behavior:
- If not import-copy only mode: we wipe the existing tokens before we run, generate a new fetch ID, tie the exceptions log entries to new fetch ID
- If import-copy only mode but ONLY fetch ID specified: we wipe the existing tokens before we run, generate a new fetch ID, tie the exceptions log entries to new fetch ID
- If import-copy only mode and BOTH fetch ID and cont token specified: we keep the existing tokens; if it succeeds, we delete the token from the exceptions log table; if it fails, we update the entry with the …

fetch: added in logic to enforce one active set of continuation tokens at a time     

---

.gitignore
cmd/fetch/fetch.go
cmd/fetch/tokens/list.go
fetch/fetch_test.go
fetch/status/exceptions.go
fetch/testdata/pg/list-tokens.ddt
fetch/token.go
go.mod
go.sum
utils/cli.go
utils/formatting.go

This feature will list out a tabular format for the continuation tokens active in the system. It will return tokens sorted based on the table name. Given that we only have one active set of tokens at a time, we do not need to do a join on the main status fetch table.
Resolves: CC-27319
**Verify Test Only Mode Works**
```
+--------------------------------------+--------------------------------------+------------------+----------------------+
|                  ID                  |               FETCH ID               |    TABLE NAME    |      FILE NAME       |
+--------------------------------------+--------------------------------------+------------------+----------------------+
| 123e4567-e89b-12d3-a456-426655440000 | 123e4567-e89b-12d3-a456-426655440000 | …
```

cmd/fetch/tokens: add in a new feature to list out all active continuation tokens

---

e2e/testdata/mysql/bool.ddt
e2e/testdata/mysql/schema_creation_dropped_constraints.ddt
e2e/testdata/mysql/uuid.ddt
e2e/testdata/pg/schema_creation.ddt
e2e/testdata/pg/schema_creation_dropped_constraints.ddt
fetch/fetch.go
fetch/schema_creation.go
fetch/schema_creation_test.go
go.mod

Now we can collect the non-primary constraints from the given table. It is logged as a warn. 
Example:
```
{"level":"warn","message":"newly created schema doesn't contain the following constraints:\ntable: public.posts,\"UNIQUE (author_id)\",\"UNIQUE (number_pg)\",\"FOREIGN KEY (tenant_id, author_id) REFERENCES users(tenant_id, user_id) ON DELETE SET NULL\",\"FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT\""}
```
Jira ticket: https://cockroachlabs.atlassian.net/browse/CC-27357
Release note: none

[CC-27357] fetch: enable fetch dropped constraints

---

.github/workflows/go.yaml
fetch/datablobstorage/gcp.go
fetch/datablobstorage/gcp_integration_test.go
fetch/datablobstorage/gcp_test.go
fetch/datablobstorage/gcp_testutil.go
fetch/datablobstorage/s3.go
fetch/datablobstorage/s3_integration_test.go
fetch/datablobstorage/s3_test.go
fetch/fetch.go
fetch/import_table.go
go.mod
go.sum

This commit adds pagination support for ListFromContinuationPoint for the AWS case. Previously we would cap out at 1000 items. But, if the item you wanted was after 1000, it wouldnt return.

fetch: Add pagination for AWS ListObjects

---

fetch/datablobstorage/copy_direct.go
fetch/fetch.go
fetch/import_table.go
fetch/status/exceptions.go
fetch/testdata/pg/continuation-edge-cases.ddt
fetch/testdata/pg/continuation.ddt

Previously, the multiple token and single-specific token case were treated differently, leading to potential continuation token loss when errors occur during non continuation logic. This means that we previously truncated the exceptions table before we even ran the import. Now, we unify the logic so that the behavior is as follows: if a table associated with a token fails, we update the associated entry with new information; if it succeeds, we remove the token. This happens within goroutines.
We also moved the connection cloning to the top of `fetchTable` so it can be used throughout the method.

fetch: unified continuation mode behavior so that specific token and multiple token behavior is the same

---

fetch/datablobstorage/gcp.go
fetch/datablobstorage/s3.go
fetch/fetch_test.go
fetch/testdata/pg/gcp.ddt
fetch/testdata/pg/s3.ddt

Now, we correctly talk to the localstack dependencies within fetch integration tests. This allows folks to write tests that use cloud stores that emulate the real resources in the cloud.

fetch: added integration for localstack gcs and s3 for fetch_test integration

---

fetch/fetch_test.go
fetch/schema_creation.go
fetch/testdata/pg/create_schema.ddt

CRDB doesn't not support [nested array](https://www.postgresql.org/docs/current/arrays.html#ARRAYS), so we need to distinguish this case can emit error.
Release note: show error if the original column is a pg nested array.

fetch/schema-creartion: distinguish nested arr type

---

fetch/export_table.go
fetch/fetch_test.go
fetch/testdata/pg/failed-export.ddt
testutils/knobs.go

Previously, when the connection for the datasource failed to be established during export, the sql writer is not closed, causing the process hangs at `record, err := r.Read()`, as it is reading from a dead but not closed pipe. This PR is to fix it, with test added. 
Release note (bug fix): during export, if the source connection fails to establish, without closing the sqlwriter will cause the whole program to hang. We fixed it by properly closing the sqlwriter. 
jira: [CC-27433](https://cockroachlabs.atlassian.net/browse/CC-27433)

fetch/export: fix bug when source connection failed to establish

---

verify/tableverify/query.go
verify/testdata/datadriven/crdb/dropped_column.ddt
verify/verify_test.go

This commit adds a attisdropped clause for pg/crdb queries when getting columnns to verify. Previously, this would return and when running LoadDataType in the PGX driver, it would cause an issue as the dropped column could not be resolved. We now omit dropped columns from being returned since we are not verifying them anyways.
Release Note: Fixes a bug for pg/crdb verify that causes an error when there are dropped columns on the table
Fixes: #187

verfiy: ignore dropped columns

---

fetch/copy.go
fetch/datablobstorage/copy_direct.go
fetch/datablobstorage/datablobstorage.go

This commit sets the 2 copy session variables required for larger copy operations. These are the same ones we currently have to set for DMS to succeed.

[CC-27525] fetch: Set copy session vars

---

build/teamcity/internal/molt/molt-nightly.sh
build/teamcity/internal/molt/setup-scale-test.sh

This setup script makes the different setup parameterized so people can customize the cluster, names, sizes, and number of nodes, etc.
Testing:
- Happy path: https://teamcity.cockroachdb.com/buildConfiguration/Internal_Molt_MoltNightly/14593335?buildTab=log&focusLine=1426&logView=linear&linesState=510
- Simulating failure: https://teamcity.cockroachdb.com/buildConfiguration/Internal_Molt_MoltNightly/14593342?buildTab=log&logFilter=debug&logView=linear&focusLine=548&linesState=513
```
[23:30:33 ](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Molt_MoltNightly/14593342?buildTab=log&logFilter=debug&logView=linear&focusLine=1433&linesState=1433)  + ./roachpad stage migrations-nightly-final release v23.2.2 --os linux
[23:30:33 …
```

scripts: added setups script for scale testing
