dbconn/dbconn.go
dbconn/pg.go

Make it more consistent with the way we do MySQL init.

refactor pg config init

---

.github/docker-compose.yml
cmd/fetch/fetch.go
dbconn/dbconn.go
dbconn/oracle.go
go.mod
go.sum
oracleconv/datatype.go
rowiterator/row_iterator.go
rowiterator/scan_iterator.go
rowiterator/scan_iterator_test.go
verify/dbverify/dbverify.go
verify/tableverify/query.go

This commit contains an initial version of oracle. It contains the bare
minimum for something to be demo'd.
It only works if:
* the schema and table names match case.
* the column names are lowercase in PG.
* The only tested types are integers and strings.
No escaping work has yet been done - but that will come - this makes the
PR a tad easier to read.
Unfortunately, CI w/ Oracle is not cooporating with me at the moment -
I'll tackle that later.

initial oracle commit

---

charts/lms/templates/lms-deployment.yaml
charts/lms/templates/orchestrator-deployment.yaml
charts/lms/values.yaml

This commit adds log level as a default to the values.

LMS: Add Log Level

---

.github/workflows/release-helm.yaml

.github/workflows: initial skeleton for the release-helm

---

.github/workflows/release-helm.yaml

Test on empty index.yaml: https://github.com/cockroachdb/molt/actions/runs/6279858063
Test on existing index.yaml: https://github.com/cockroachdb/molt/actions/runs/6279864587/job/17056238231

.github/workflows: updated so that we remove potential erroneous index file

---

charts/lms/templates/orchestrator-deployment.yaml

This commit adds the right env var that needs to be set in order to read from a mounted secret.

LMS: Fix Orch Secret Reading

---

docker/mysql-init/mysql-init.sql
docker/pg-init/pg-init.sql

Bulk insert data for the mysql and pg source data so that it's easier to test.

docker: added in logic to seed the DB within the container with starter data

---

docker/cockroach-init/cockroach-init.sql
docker/docker-compose.yml

docker: added cockroach and init for the docker-compose setup

---

demo/README.md
demo/cockroach/cockroach-init.sql
demo/docker-compose.yml
demo/grafana/dashboard.json
demo/grafana/dashboard.yaml
demo/grafana/datasource.yml
demo/nginx/lms.conf
demo/nginx/nginx.conf
demo/prometheus/prometheus.yml

This commit adds the start to what could be the mega demo. It spins up the LMS with 3 nodes and the respective databases to do what the k8s demo does.

demo: LMS docker demo

---

.github/workflows/release.yaml

.github/workflows: fix base versions so that they're pulled from the bucket

---

README.md
cmd/escape_password.go
cmd/root.go

README: added in instructions for encoding passwords

---

.github/workflows/go.yaml

workflows: add commit sha to the test output

---

README.md

README: fixed typo

---

cmd/fetch/fetch.go

fetch: fixed broken default compression behavior

---

README.md

Based on:
1. https://github.com/cockroachdb/molt/issues/93
2. https://cockroachlabs.slack.com/archives/C04TQ67V1JL/p1701871210926509
Release note: Updated the readme for a OS + docker based edge case with fetch.

fetch: add edge case explanation for time drift

---

README.md

fetch: fix typo in the README

---

docs/RFCS/00000000_template.md
docs/RFCS/20231113_molt_fetch.md

docs/RFCS: added template for RFCs and initial MOLT fetch RFC

---

.gitignore

molt: removed task.log and added gitignore

---

.gitignore

molt: removed unnecessary log files and added git ignore rules

---

e2e/testdata/crdb/simple_fetch_verify.ddt
e2e/testdata/mysql/simple_fetch_verify.ddt
e2e/testdata/pg/simple_fetch_verify.ddt
fetch/fetch.go

To fix the failed e2e test on dev: https://github.com/cockroachdb/molt/actions/runs/7535274222

fetch: update e2e test for net duration entry

---

fetch/status/exceptions.go
fetch/status/exceptions_test.go

The helpers query the database in order to get the relevant exception logs for a given continuation token or the fetch ID that one wants to resume from. These end up helping the user to figure out how they can continue from where they left off.
Resolves: CC-26910

fetch: added in helpers to exception logs to fetch exception logs by ID or the most recent ones by table

---

fetch/status/exceptions.go
fetch/status/exceptions_test.go

Exceptions logging file name regexer is now more clean and specific now. Added new test cases and negative test cases for this.

fetch: replaced regex to be more specific and also include support for tar.gz

---

fetch/csv_pipe_test.go

This commit updates the unit test in csv_pipe to check the rows per batch that it gets back matches the result sent over the numRows channel
Release Note: none

fetch: Update csv_pipe test to include row count

---

fetch/csv_pipe_test.go

To ensure that goroutines where the numrows are push to the channel happens one
by one, i.e. no concurrent goroutines.

fetch: fix csv_pipe test

---

e2e/testdata/crdb/simple_fetch_verify.ddt
e2e/testdata/mysql/simple_fetch_verify.ddt
e2e/testdata/pg/simple_fetch_verify.ddt

This commit rewrites the e2e tests from changes due to adding row count.
Release Note: none

e2e: Rewrite tests

---

fetch/datablobstorage/gcp.go
fetch/datablobstorage/gcp_test.go
fetch/datablobstorage/s3.go
fetch/datablobstorage/s3_test.go

fetch: added testing for missing metadata row case + updates to error handling logic

---

cmd/fetch/fetch.go
cmd/internal/cmdutil/pprof.go
fetch/export_table.go
fetch/pipe.go

Fetch: Pipe Fix/Add Pprof

---

docs/RFCS/20231113_molt_fetch.md

revise COPY TO to COPY FROM in Fetch RFC

---

README.md

README: added in links to releases

---

cmd/fetch/fetch.go

This commit consolidates the s3-bucket and gcp-bucket flag into just one bucket-path flag to make things less confusing. Now users can just specify the direct uri to the bucket which is the standard format of s3://bucket/path or gs://bucket/path with the bucket-path flag.
Release Note: Deprecates s3-bucket and gcp-bucket flag for just bucket-path

[CC-27235] fetch: Consolidate s3-bucket and gcp-bucket flag

---

.github/docker-compose.yml
cmd/fetch/fetch.go
fetch/datablobstorage/datablobstorage.go
fetch/datablobstorage/gcp.go
fetch/datablobstorage/s3.go
fetch/export_table_test.go

This commit adds localstack/fakegcs so we can test without using real infra

fetch: Add localstack

---

e2e/testdata/mysql/schema_creation_dropped_constraints.ddt
e2e/testdata/pg/schema_creation_dropped_constraints.ddt

fetch: add non-interactive flag to schema creation dropped constraint e2e tests

---

fetch/copy.go
fetch/import_table.go

Previously, Jane highlighted that if a connection dies while processing a copy or import, the exception log cannot be successfully written if the same conneciton is used. In order to avoid this case, we create a clone of this connection before we use it to record the exception.

fetch: use a cloned connection for exceptions log reporting

---

fetch/export_table.go
fetch/fetch_test.go
fetch/testdata/pg/failed-export.ddt
testutils/knobs.go

😅 😅 😅 😅 😅 😅 
Merged the PR too soon. The commit message of #179 was not updated yet. Sorry for spamming 😅 
😅 😅 😅 😅 😅 😅

fetch/export: fix commit message

---

README.md
cmd/fetch/fetch.go
demo/docker-compose.yml
fetch/fetch.go
fetch/fetch_test.go
fetch/testdata/crdb/basic.ddt
fetch/testdata/mysql/basic.ddt
fetch/testdata/mysql/exceptions.ddt
fetch/testdata/pg/basic.ddt
fetch/testdata/pg/constraint-exceptions.ddt
fetch/testdata/pg/continuation-edge-cases.ddt
fetch/testdata/pg/continuation-shards.ddt
fetch/testdata/pg/continuation.ddt
fetch/testdata/pg/exceptions.ddt
fetch/testdata/pg/list-tokens.ddt

This commit adjusts the copy for some of the flag names based on a meeting that we had.
Release notes: Live,concurrency, and shards flag have been renamed.

[CC-27236] fetch: Copy Edits

---

.github/workflows/release.yaml
cmd/apiversion.go
cmd/root.go
e2e/testdata/pg/simple_fetch_verify.ddt
scripts/replace-api-version.sh

cmd: support --version flag
